version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network  # Ensure both containers are in this network

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge  # This creates a bridge network for both containers

environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080